// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"FlashCardsBackEnd/internal/config/validator"
	"FlashCardsBackEnd/internal/infra/mongodb"
	"FlashCardsBackEnd/pkg"
	"FlashCardsBackEnd/pkg/api/handler/playlist_handler"
	"FlashCardsBackEnd/pkg/api/routers"
	"FlashCardsBackEnd/pkg/repository/playlist_repository"
	"FlashCardsBackEnd/pkg/usecase/playlist_usecase"
)

// Injectors from wire.go:

func SetupApplication() (pkg.Application, error) {
	client, err := mongodb.NewMongoDbClient()
	if err != nil {
		return pkg.Application{}, err
	}
	playlistRepository := playlist_repository.NewPlaylistRepository(client)
	validate := validator.NewValidate()
	playlistUseCase := playlist_usecase.NewPlaylistUseCase(playlistRepository, validate)
	playlistHandler := playlist_handler.NewPlaylistHandler(playlistUseCase)
	systemRoutes := routers.NewSystemRoutes(playlistHandler)
	application := pkg.NewApplication(systemRoutes)
	return application, nil
}
